FROM ubuntu:24.04

COPY gitconfig /root/.gitconfig

RUN apt-get update \
	&& apt-get install -y software-properties-common

RUN add-apt-repository ppa:neovim-ppa/unstable \
	&& apt-get update \
	&& apt-get install -y neovim

RUN apt-get update \
	&& apt-get install -y python3-dev python3-pip git

RUN mkdir -p /root/.ssh && ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN mkdir -p /opt/.config

RUN apt-get update && apt-get install -y \
	git \
	unzip \
	make \
	cmake \
	gcc \
	g++ \
	clang \
	zoxide \
	ripgrep \
	fd-find \
	fzf \
	yarn \
	lldb \
	curl \
	python3-pip \
	python3-venv \
	golang \
	openjdk-21-jdk

# Docker
RUN curl -sSf https://get.docker.com | sh

# Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && . /root/.bashrc \
	&& cargo install tree-sitter-cli \
	&& cargo install starship

# Nvim
RUN git clone https://github.com/Kraust/nvimdots.git /opt/.config/nvim

# Go
RUN git clone https://github.com/go-nv/goenv.git /opt/.goenv

# Python
RUN git clone https://github.com/pyenv/pyenv.git /opt/.pyenv

# Node
RUN git clone https://github.com/nodenv/nodenv.git /opt/.nodenv

ENV TARGET_DIR=/root/.local/xonsh-env 
ENV PYTHON_VER=3.11 
ENV XONSH_VER='xonsh[full]>=0.19.0'
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/anki-code/xonsh-install/main/mamba-install-xonsh.sh)"
RUN git clone https://github.com/Kraust/xonsh.git /opt/.config/xonsh
ENV SHELL=/root/.local/xonsh-env/bin/xonsh

ENV PATH="$PATH:/root/.local/xonsh-env/bin"
ENV PATH="$PATH:/root/.cargo/bin"
ENV PATH="$PATH:/root/bin"
ENV PATH="$PATH:/root/.config/bin"
ENV PATH="$PATH:/root/.pyenv/bin"
ENV PATH="$PATH:/root/.goenv/bin"
ENV PATH="$PATH:/root/.nodenv/bin"

COPY entrypoint.xsh /opt/entrypoint.xsh
RUN chmod +x /opt/entrypoint.xsh

SHELL ["/root/.local/xonsh-env/bin/xonsh", "-c"]
ENTRYPOINT ["/opt/entrypoint.xsh"]
