services:
  dev_cockpit:
    image: dev-cockpit:latest
    container_name: dev_cockpit
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home:/home
      - /home3:/home3
      - /Eng:/Eng
      - root:/root
    working_dir: /root
volumes:
  root:
