services:
  dev_cockpit:
    image: dev-cockpit:latest
    container_name: dev_cockpit
    privileged: true
    network_mode: host
    restart: always
    environment:
      - GIT_CONFIG_GLOBAL=/root/.config/gitconfig/gitconfig
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.config/gitconfig:/opt/.config/gitconfig
      - /home:/home
      - /home3:/home3
      - /Eng:/Eng
      - root:/root
    working_dir: /
volumes:
  root:
